### ISSUE TITLE
Selection of item in list with click?

### ISSUE THREAD

**Issue by rakkarage** [dmo60/CoverflowAltTab#126]
Thanks a lot! Looks great!

When i press alt+tab in gnome i can then selected one of the items in the list with click to select it.
Is there (could there be) a way to to the same using this?
Thanks.

**Comment by dsheeler** [comment]
How do you envision that working?  You must mean by having all the items displayed at once as they are by default, is that correct?

**Comment by rakkarage** [comment]
ya you can press alt+tab to show list of running programs and keep showing that list by holding alt+tab
but it seems you cannot click on a running program to select it you must use keyboard?
thanks

**Comment by dsheeler** [comment]
Well, this one works where if you press alt+tab, release tab but hold alt, then pressing tab again gives you the next app, and once you reach the app you want, letting go of alt brings that one forward.  There is mousewheel for cycling, too.   Does that work for you?  I guess there could be an option for showing the default behavior as well.  That might be cool to have.  But the way things are displayed, it would be hard to click on anything other than the current one.

**Comment by rakkarage** [comment]
![Peek 2020-05-01 20-54](https://user-images.githubusercontent.com/962340/80851202-3079fe00-8bee-11ea-997d-3ad41bacfb4a.gif)

**Comment by dsheeler** [comment]
Ahh, I see.  I use the other mode where clicking isn't as easy.

**Comment by dsheeler** [comment]
@rakkarage, I'm about to make this happen

**Comment by dsheeler** [comment]
https://user-images.githubusercontent.com/1632985/177895141-9f61aa66-a52b-4f40-8e10-dbe3918869d0.mp4

So this demos a couple things about the timeline switcher: the front window eases to a 0 degree angle  unlike above where every window has the same angle away from 0.  Do you like that?  Also, I have mouse-over events pulling a window to the top and easing it to a zero degree angle and to 120% its up-front size.  That might be too much, but it's useful to see the contents of very far back windows.  Any thoughts or suggestions on this?

**Comment by machitgarha** [comment]
@dsheeler, although I wouldn't use the feature, but this is great! The details of the feature can be improved further for sure, but that's a good starting point. Thank you!

**Comment by dsheeler** [comment]
@machitgarha, I want a way to highlight the window that would be selected by a click. Do you have a suggestion on how to do that? Color, effect, size, orientation, or otherwise?

**Comment by machitgarha** [comment]
@dsheeler, I think changing the title box should always happen. It might seem obvious, the effect on window itself (or possibly other windows) should be different in Coverflow and Timeline styles.

In Coverflow mode, I suggest you to have the same effect as keyboard navigation, but without any scroll. So for example, highlighting a window causes the alt-tab-focused window to be moved aside, the mouse-highlighted window to be moved to the top (i.e. `CoverflowSwitcher::animatePreviewToMid()`), and the possible middle windows to be flipped. It may be hard to implement it and the scroll event at the same time, however, as you might want to act differently than keyboard navigation.

In Timeline mode, I think the current base idea is nice, just you need to be sure all windows are accessible, even the smallest-sized ones. In order to do this, one simple idea is to align windows to the left, so all of them become visible.

**Comment by bitnom** [comment]
+1 for wanting clicking feature. Sometimes it's just faster, especially when your mouse pointer already happens to be near your target window.

**Comment by dsheeler** [comment]
Windows are clickable in the current version for download!
