### ISSUE TITLE
Preferences broken in gnome-shell < 4.0

### ISSUE THREAD

**Issue by sengelsman** [dmo60/CoverflowAltTab#150]
OS: Ubuntu 20.10
Gnome-shell: 3.38.2-1ubuntu1~20.10.1
CoverflowAltTab: Release 1.11

After updating to latest release (1.11) the preferences screen is not shown. Instead i get the following exception:

```
TypeError: frame.append is not a function

Stack trace:
  buildPrefsWidget@/home/simon/.local/share/gnome-shell/extensions/CoverflowAltTab@dmo60.de/prefs.js:70:15
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```
Comparing `prefs.js` from release 1.10 and 1.11 i notice that gnome-shell 4 support was added, effectively breaking support for older versions.

**Comment by p91paul** [comment]
That's correct. My policy is to support only the latest Gnome version, as they break stuff too often and I don't have the resources to keep supporting older versions too.
You should use the extension version with support for your gnome version; if you install from extensions.gnome.org that will be handled for you automatically, otherwise just stick to the right git tag.
