### ISSUE TITLE
The windows on dual monitors only show on one side

### ISSUE THREAD

**Issue by lomirus** [dmo60/CoverflowAltTab#173]
![](https://i.imgur.com/j3eWGHS.jpg)

I use the dual-monitor, but on such situation you can see from the image above that in the right screen, only the right side of it shows the windows. Though the windows on the left side are still there, they nearly became stripes.

**Comment by sammdu** [comment]
Same issue here! bumping for visibility.

I have my external monitor on the left, so for me, it's the right side that has thumbnails way too thin:

![coverflow-alt-tab-issue_1440](https://user-images.githubusercontent.com/10665890/188345692-5fec0ffc-b687-49b0-9dd3-74c2cc6be1d2.png)

**Comment by dsheeler** [comment]
What would you think of putting it in the middle of the two monitor split?

**Comment by sammdu** [comment]
@dsheeler I'm not sure that's a good idea. I use my monitors separately, rather than as one continuous piece. 
I would prefer if it just behaved the same way it would on a single monitor.

**Comment by dsheeler** [comment]
I've taken a stab at fixing this in d935e3d325991246021041461f61285185a7efc0. Could you checkout that commit and try the code?  It works for me, heh. Or, if you have github cli, you can run `% gh pr checkout 178`

**Comment by dsheeler** [comment]
On my dual monitor setup, it works on both monitors.

![Screenshot-20221118011138-smaller](https://user-images.githubusercontent.com/1632985/202645201-4f0be80b-5386-47d7-841e-95a736e1e250.png)
![Screenshot-20221118012657-smaller](https://user-images.githubusercontent.com/1632985/202646179-62a58808-0eab-4455-b981-2393a8d74b66.png)

**Comment by dsheeler** [comment]
Also works for me on three monitor setup.

**Comment by sammdu** [comment]
@dsheeler Thanks so much for looking into this!

I checked out your commit and copied the folder to my extensions directory. Unfortunately, the behavior is still weird:

![Screenshot-20221118164718-7680x2160_ds](https://user-images.githubusercontent.com/10665890/202809382-c75c644d-171b-4af1-95a6-afcbfc7d7581.png)

- the window on the right gets stretched very wide, and ends up behind the center window
- the window on the left spills over to my left monitor

* * *
Similar thing on my left monitor:

![Screenshot-20221118165711-7680x2160_ds](https://user-images.githubusercontent.com/10665890/202810082-b562ee22-65e4-40fa-b9b3-341e676b99d7.png)

**Comment by dsheeler** [comment]
@sammdu, What resolution are you using?

**Comment by sammdu** [comment]
@dsheeler 3840x2160, at 200% scale.

**Comment by dsheeler** [comment]
@sammdu, could you try the latest on the `perspective-correction-for-off-center-monitors` branch?  I think it will work for you, now.

**Comment by sammdu** [comment]
@dsheeler Thanks so much! Yes, the animation is working correctly this time!

There's one small thing though, large windows (maximized) remain large and end up covering the most of the screen. It would be better if large windows are scaled down so that other windows on the left and right can remain visible.
Other than that it's great!

**Comment by dsheeler** [comment]
@sammdu, there's actually a setting for that: "Ratio of preview to monitor size"

I keep mine at 50%. Maybe you could suggest a better name if you didn't think that setting affects that.

![Screenshot-20221122110556-762x698](https://user-images.githubusercontent.com/1632985/203377060-a1fcf257-2e25-4103-8768-d85af960a19c.png)

**Comment by sammdu** [comment]
@dsheeler Ah got it! Thanks for pointing this out. Now it's perfect!

I think the name is perfect, but perhaps set it to 50% by default? 
(It's also possible I just messed with the settings and forgot about it :/)

**Comment by lomirus** [comment]
Looks like the fixed version has not been published yet on https://extensions.gnome.org/. @dsheeler Do you have the permission to publish it?

**Comment by dsheeler** [comment]
@lomirus, I have been experimenting with another way to correct perspective, and have been holding off on this, but I'll do it soon.

**Comment by dsheeler** [comment]
@sammdu, thank you for suggesting changing the default. I just released a new version on ego that changes the default to 50% which is pretty close to what most users would want. Cheers!

**Comment by dsheeler** [comment]
@lomirus, I just published a version with two ways to address this issue. This is an [issue of perspecive](https://www.youtube.com/watch?v=dpYyn1BXGjU), and I stole this method of moving the camera in front of an off-center monitor from the Desktop Cube extension. Amazeballs. The first solution I came up with was just to rotate the windows such that they look correct even though they are off-center. I just used trial and error angles and hardcoded them, so that will only work on 16.9 resolution, I think. The camera moving technique is great when things are stationary but has some issues drawing while windows rotate. They both fail to correctly pick the window under the mouse, so this is hardly ideally solved, but it's a start.
