### ISSUE TITLE
Support for GNOME 3.18

### ISSUE THREAD

**Issue by Bob131** [dmo60/CoverflowAltTab#45]
Hey! I tried changing the shell-version attr in metadata.json, but the effect resulted in graphical artefacts requiring me to restart GNOME Shell for it to regain usability. Its possible that is down to the use of dual GPUs rather than the new shell, hopefully you can work that out better than I :)

Great bit of eyecandy, thanks for your efforts!

**Comment by dffischer** [comment]
[It works flawless for me](https://github.com/dmo60/CoverflowAltTab/pull/46), on an Arch Linux with a single integrated Intel GPU.

**Comment by frol** [comment]
I confirm that it works on Arch Linux on my dual GPUs laptop (Intel HD4600 + Nvidia) with Gnome 3.18 and now 3.20 without any artifacts.

**Comment by SalahAdDin** [comment]
But, this extension are outdated.

**Comment by p91paul** [comment]
I believe @frol means that no code changes are required to make it work; #55 confirms this (actually this issue should be closed since 3.18 support is in the master branch and for 3.20 #56 duplicates #55). You can modify metadata.json to add 3.20 (like #55 does) while @dm60 takes care of merging and uploading to extensions.gnome.org (where it needs to be reviewed as well)

**Comment by p91paul** [comment]
Extension is up to date on extensions.gnome.org now!
