### ISSUE TITLE
Per-monitor tab switching

### ISSUE THREAD

**Issue by MatteCarra** [dmo60/CoverflowAltTab#80]
It would be great to be able to switch applications only on the current active monitor.
Is there already a way to do it?
Thanks in advance

**Comment by p91paul** [comment]
Hi, there is https://github.com/dmo60/CoverflowAltTab/pull/53 to address this. Are you able to test it to check if it works properly? I never found the time to review that pull request.

**Comment by MatteCarra** [comment]
I've just tried it and it works. If I find any bug I will report it.

**Comment by MatteCarra** [comment]
The only negative thing is that the active monitor is the one where the mouse is, but @pospeselr designed it like so.

**Comment by p91paul** [comment]
what should be considered active instead? where the mouse is seems pretty reasonable to me!

**Comment by MatteCarra** [comment]
I think that current approach is very good after all.
Anyway I think that the active monitor is the one with the active window in it, where text is inserted when you type or where alt-f4 and other commands have effects, despite the position of the cursor.

**Comment by p91paul** [comment]
Pull request has been merged.
For the definition of "current monitor" I decided not to rely on cursor position calculations but in Gnome Shell own API (there is an object `Main.layoutManager.currentMonitor`).
Turns out they agree with @pospeselr, at least from my testing.

Sorry for the long time it took to close this, when initial Gnome 40 compatibility is approved on e.g.o. I'll probably issue another upload with this. It will be available on Gnome 40+ only.
