### ISSUE TITLE
Extension is not compatible with current Cinnamon version (Cinnamon 4.0.2)

### ISSUE THREAD

**Issue by Heterodyne** [dmo60/CoverflowAltTab#93]
What do I need to add in extension.js for 4.0.2 ?

**Comment by p91paul** [comment]
mmm modifying metadata.json is not enough? journalctl reports some errors?
Possibly changes to support gs 3.30 broke it for cinnamon...

**Comment by Heterodyne** [comment]
No....
                                                    <----------------
                                                    logError@/usr/share/cinnamon/js/ui/extension.js:134:17
                                                    prepareExtensionUnload@/usr/share/cinnamon/js/ui/extensionSystem.js:37:9
                                                    unloadExtension@/usr/share/cinnamon/js/ui/extension.js:529:13
                                                    unloadRemovedExtensions@/usr/share/cinnamon/js/ui/extensionSystem.js:124:13
                                                    onEnabledExtensionsChanged@/usr/share/cinnamon/js/ui/extensionSystem.js:105:5
                                                    ---------------->

**Comment by p91paul** [comment]
I merged https://github.com/dmo60/CoverflowAltTab/pull/145 and decided to drop Cinnamon support.
This extension, or most of it at least, should be part of cinnamon anyway; I'm aware that this extension provided more options that the cinnamon builtin, but I'm not a cinnamon user and I'm unable to provide support for it due to limited time.
If anyone wants to contribute working cinnamon code, it will be welcome. Infrastructure to support multiple platforms should be ready in platform.js.
